apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins
type: Opaque
data:
  GITHUB_USERNAME: Z2l0aHViX3VzZXJuYW1l
  GITHUB_PASSWORD: Z2l0aHViX3Bhc3N3b3Jk
  DOCKERHUB_USERNAME: ZG9ja2VyaHViX3VzZXJuYW1l
  DOCKERHUB_PASSWORD: ZG9ja2VyaHViX3Bhc3N3b3Jk
  SNYK_TOKEN: c3lua190b2tlbg==